### ISSUE TITLE
There isn't usb-c connector (TYPE-C-31-M-12) in the position file.

### ISSUE THREAD

**Issue by kinmojr** [ai03-2725/Unified-Daughterboard#10]
There isn't usb-c connector (TYPE-C-31-M-12) in the position file.
https://github.com/ai03-2725/Unified-Daughterboard/blob/master/Production/C3/Position/Unified-Daughterboard-all.pos
Would you tell me the position of usb-c connector ?

**Comment by TweetyDaBird** [comment]
That most likely means it wasn’t machine mounted in that instance. A perfectly reasonable cost saving measure since it’s ‘easy’ bough to hand solder. 

Go into the project and export the position files from there, and it is included.

**Comment by kinmojr** [comment]
I did it on KiCad 5.1, but there isn't usb-c connector in the position file.
Do I need any settings or something to output the usb-c connector?
Thanks.
